[package]
name = "maturin"
version = "0.1.0"
authors = ["scpointer <956096260@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.5"
bitflags = "1.2.1"
xmas-elf = "0.7"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
lock = { git = "https://gitee.com/chyyuu/kernel-sync.git"}
riscv = { git = "https://gitee.com/chyyuu/riscv.git", features = ["inline-asm"] }
bitmap-allocator = { git = "https://gitee.com/chyyuu/bitmap-allocator.git" }