[package]
name = "range-action-map"
version = "0.1.4"
authors = ["scpointer <jax01@foxmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []
default = ["std"]

[dependencies]
